name: Build wheels

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  checkout:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          torchaudio-version:
            - 'v2.0.2'
    steps:
      - name: Checkout self
        uses: actions/checkout@v4
        with:
          path: self
      - name: Checkout torchaudio
        uses: actions/checkout@v4
        with:
          repository: pytorch/audio
          ref: ${{ matrix.torchaudio-version }}
          path: torchaudio
      - name: Upload self
        uses: actions/upload-artifact@v3
        with:
          name: self
          path: self
      - name: Upload torchaudio
        uses: actions/upload-artifact@v3
        with:
          name: torchaudio-${{ matrix.torchaudio-version }}
          path: torchaudio
  build-linux:
    needs: checkout
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.9'
        torchaudio-version:
          - 'v2.0.2'
        image:
          - "quay.io/pypa/manylinux2014_x86_64"
        include:
          - torchaudio-version: 'v2.0.2'
            torch-version: '2.0.1'
          - python_version: "3.9"
            abi_tag: "cp39-cp39"
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Download self
        uses: actions/download-artifact@v3
        with:
          name: self
          path: self
      - name: Download torchaudio src
        uses: actions/download-artifact@v3
        with:
          name: torchaudio-${{ matrix.torchaudio-version }}
          path: torchaudio
      - name: Install build tools
        shell: bash -el {0}
        run: |
          sudo apt install cmake ninja
      - name: Install torch
        shell: bash -el {0}
        run: |
          /opt/python/${{ matrix.abi_tag }}/bin/pip install --only-binary torch --index-url https://download.pytorch.org/whl/cpu-cxx11-abi torch==${{ matrix.torch-version }}
      - name: Build using setuptools
        shell: bash -el {0}
        run: |
          cd torchaudio
          _GLIBCXX_USE_CXX11_ABI=1 /opt/python/${{ matrix.abi_tag }}/bin/python setup.py bdist_wheel

      - name: Upload distribution
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: torchaudio/dist/
