name: Build wheels

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  checkout:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout self
        uses: actions/checkout@v4
        with:
          path: self
      - name: Upload self
        uses: actions/upload-artifact@v4
        with:
          name: self
          path: self
  build-linux:
    needs: checkout
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - '3.9'
        torchaudio-version:
          - '2.0.2'
          - '2.2.2'
        include:
          - torchaudio-version: '2.0.2'
            torch-version: '2.0.1'
          - torchaudio-version: '2.2.2'
            torch-version: '2.2.2'
    steps:
      - name: Download self
        uses: actions/download-artifact@v4
        with:
          name: self
          path: self
      - name: Checkout torchaudio
        uses: actions/checkout@v4
        with:
          repository: pytorch/audio
          ref: v${{ matrix.torchaudio-version }}
          path: torchaudio
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: torchaudio-build
          environment-file: self/environment-py${{ matrix.python-version }}.yml
          use-only-tar-bz2: true # This needs to be set for caching to work properly
          auto-activate-base: false
      - name: Install torch
        shell: bash -el {0}
        run: |
          pip install --only-binary torch --index-url https://download.pytorch.org/whl/cpu-cxx11-abi torch==${{ matrix.torch-version }}
      - name: Build using setuptools
        shell: bash -el {0}
        run: |
          cd torchaudio
          _GLIBCXX_USE_CXX11_ABI=1 BUILD_VERSION=${{ matrix.torchaudio-version }} python setup.py bdist_wheel

      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.torchaudio-version }}
          path: torchaudio/dist/
