name: Build wheels

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.9'
        torchaudio-version:
          - 'v2.0.2'
        image:
          - "quay.io/pypa/manylinux2014_x86_64"
        include:
          - torchaudio-version: 'v2.0.2'
            torch-version: '2.0.1'
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout self
        uses: actions/checkout@v4
        with:
          path: self
      - name: Checkout torchaudio src
        uses: actions/checkout@v4
        with:
          repository: pytorch/audio
          ref: ${{ matrix.torchaudio-version }}
          path: torchaudio
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: torchaudio-build
          environment-file: self/environment-py${{ matrix.python-version }}.yml
          use-only-tar-bz2: true # This needs to be set for caching to work properly
          auto-activate-base: false
      - name: Print conda
        shell: bash -el {0}
        run: |
          conda list
      - name: Install torch
        shell: bash -el {0}
        run: |
          pip install --only-binary torch --index-url https://download.pytorch.org/whl/cpu-cxx11-abi torch==${{ matrix.torch-version }}
      - name: Build using setuptools
        shell: bash -el {0}
        run: |
          cd torchaudio
          _GLIBCXX_USE_CXX11_ABI=1 python setup.py bdist_wheel

      - name: Upload distribution
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: torchaudio/dist/
