name: Publish Wheels

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  run-build-workflow:
    uses: ./.github/workflows/build.yml

  pypi-publish:
    name: Publish to PyPi
    needs: run-build-workflow
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist/
        pattern: dist-*
        merge-multiple: true
    - name: List artifacts downloaded
      run: ls -R dist
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1.8
      with:
        verbose: true
        verify-metadata: false  # twine bug causing issues so disable
